name: My Android Workflow # Name of the Action

on: [push, pull_request] # List of events that trigger the Action

jobs: # List of jobs that will be run on the code
  test:
    runs-on: macos-latest # Container of choice
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: ./gradlew connectedCheck
